# LLM Sentiment analisis

In [ ]:
# python 3.13.3
# !pip install openai==1.3.9
import openai
print(openai.__version__)



1.86.0


In [2]:
#ติดตั้งไลบรารีที่จำเป็น
# !pip install openai pandas tqdm scikit-learn
# !pip install python-dotenv
# นำเข้าไลบรารี
import pandas as pd
from openai import OpenAI
from tqdm import tqdm
import time
from sklearn.model_selection import train_test_split
from dotenv import load_dotenv
import os

load_dotenv()


api_key = os.getenv("OPENROUTER_API_KEY")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,  
)

MODEL = "scb10x/llama3.1-typhoon2-70b-instruct"

# โหลดข้อมูล
df = pd.read_excel(r'C:\Users\FOth-PC\Desktop\เอกสาร\Ruby-test\rawdata_sentiment.xlsx') 

# ถ้า column ชื่ออื่น เปลี่ยนชื่อให้ตรง เช่น df.rename(columns={'Review': 'review', 'Label': 'label'}, inplace=True)
# df.rename(columns={'Text': 'review', 'Sentiment': 'label'}, inplace=True)

train_df, valid_df = train_test_split(
    df, test_size=0.2, stratify=df['Sentiment'], random_state=0
)
train_df = train_df.reset_index(drop=True)
valid_df = valid_df.reset_index(drop=True)
print('valid_df size', valid_df.size)
df.head()

valid_df size 1200


Text Sentiment
0                                      นี้ๆชวนบ่อยสะ       neu
1  (พยาบาลพัฒนาระบบคุณภาพ), โรงพยาบาลกรุงเทพภูเก็...       neu
2  เคยเจอแบบนี้ตอนนั่งแท็กซี่กลับจากคอนเสิร์ตคนเด...       neu
3                                        นิสสันมาแหะ       neu
4                                  อยากกินอ่ะหมู 😣😣😣       pos

In [3]:
# 5. สร้างฟังก์ชันเรียก OpenRouter LLM
def classify_sentiment(review, retry=2):
    prompt = f"""Classify the following review as Positive, Neutral, or Negative. Only output the label.

Review: "{review}"
Sentiment:"""
    for _ in range(retry):
        try:
            completion = client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                max_tokens=3
            )
            return completion.choices[0].message.content.strip()
        except Exception as e:
            print("Error:", e)
            time.sleep(2)
    return "error"


In [6]:
#few-shot prompt
import numpy as np

label_names = ['neu', 'pos', 'neg']
n_per_label = 1
fewshot_list = []

for label in label_names:
    sample = train_df[train_df['Sentiment'] == label].sample(n=n_per_label, random_state=42)
    for _, row in sample.iterrows():
        fewshot_list.append(f'Review: "{row["Text"]}" Label: {row["Sentiment"]}')

fewshot_prompt = '\n'.join(fewshot_list)

def ask_llm_with_fewshot(review, fewshot_prompt, model=MODEL, max_retry=2):
    prompt = f"""{fewshot_prompt}
Review: "{review}"
Label:"""
    for _ in range(max_retry):
        try:
            completion = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                max_tokens=3
            )
            return completion.choices[0].message.content.strip().lower()
        except Exception as e:
            print("Error:", e)
            time.sleep(2)
    return "error"



In [7]:
from tqdm import tqdm

valid_part = valid_df.sample(n=1, random_state=42)  # หรือจะวนทุกแถวก็ได้ (แต่ช้า)
results = []
for review in tqdm(valid_part["Text"]):
    results.append(ask_llm_with_fewshot(review, fewshot_prompt))

valid_part['llm_pred'] = results

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_true = valid_part["Sentiment"].str.lower()
y_pred = valid_part['llm_pred']

print("\nAccuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred, digits=3))
print("Confusion matrix:\n", confusion_matrix(y_true, y_pred, labels=label_names))

100%|██████████| 1/1 [00:02<00:00,  2.76s/it]


Accuracy: 0.0
              precision    recall  f1-score   support

         neg      0.000     0.000     0.000       1.0
         neu      0.000     0.000     0.000       0.0

    accuracy                          0.000       1.0
   macro avg      0.000     0.000     0.000       1.0
weighted avg      0.000     0.000     0.000       1.0

Confusion matrix:
 [[0 0 0]
 [0 0 0]
 [1 0 0]]



C:\Users\FOth-PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\FOth-PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\FOth-PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_class

In [8]:
valid_part.to_csv("llm_valid_with_pred.csv", index=False, encoding="utf-8-sig")